((nil . ((indent-tabs-mode . nil)
	 (tab-width . 8)
         ;;(coding . utf8)
	 (fill-column . 92)
	 (ispell-local-dictionary . "american")))
 (julia-mode . ())
 (sh-mode . ((sh-basic-offset . 4))))
